# Generated by Django 3.1.7 on 2021-07-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tony_blogs', '0004_auto_20210401_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
