# Generated by Django 3.1.7 on 2021-08-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tony_blogs', '0006_user_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_comment',
            options={},
        ),
        migrations.AlterField(
            model_name='user_comment',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
