# Generated by Django 3.1.7 on 2021-08-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tony_blogs', '0007_auto_20210814_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tony_blogs.blog'),
        ),
    ]
