# Generated by Django 3.1.7 on 2021-09-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tony_blogs', '0008_auto_20210814_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tony_blogs.blog'),
        ),
    ]
