# Generated by Django 3.1.7 on 2021-11-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tony_blogs', '0009_auto_20210916_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_comment',
        ),
    ]
